name: Docs
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip  
          python3 -m pip install mkdocs      
          python3 -m pip install mkdocs-material
          python3 -m pip install pymdown-extensions
          python3 -m pip install mkdocs-git-revision-date-localized-plugin
      - name: Build site
        run: |
          git config user.name "yashlamba" && git config user.email "yashlamba2000@gmail.com"
          git fetch origin
          mkdocs build
          git clone -b latestweb https://github.com/yashlamba/deployingexp/ web/
          mv web/web/ site/
          mkdocs gh-deploy --dirty
